//
// Generated by Microsoft (R) HLSL Shader Compiler 9.29.952.3111
//
// Parameters:
//
//   float4 CameraPositionVS;
//   float4 FogInScattering[4];
//   float4 FogMaxHeight;
//   float3 InstancedPreViewTranslation;
//   float3 MeshExtension;
//   float3 MeshOrigin;
//   float4 SharedFogParameter0;
//   float4 SharedFogParameter1;
//   float4 SharedFogParameter2;
//   float4 SharedFogParameter3;
//   float4x4 ViewProjectionMatrix;
//   float bUseExponentialHeightFog;
//
//
// Registers:
//
//   Name                        Reg   Size
//   --------------------------- ----- ----
//   ViewProjectionMatrix        c0       4
//   CameraPositionVS            c4       1
//   FogInScattering             c6       4
//   InstancedPreViewTranslation c10      1
//   MeshOrigin                  c11      1  0
//   MeshExtension               c12      1  // 1
//   SharedFogParameter0         c13      1
//   SharedFogParameter1         c14      1
//   SharedFogParameter2         c15      1
//   SharedFogParameter3         c16      1
//   bUseExponentialHeightFog    c17      1
//   FogMaxHeight                c18      1
//

vs_3_0
def c5, 0.00784313772, -1, 0, 0.00999999978
def c19, 0.499000013, 0.5, 0.00100000005, 0
dcl_position v0
dcl_tangent v1
dcl_normal v2
dcl_color1 v3
dcl_texcoord v4
dcl_texcoord1 v5
dcl_texcoord2 v6
dcl_texcoord3 v7
dcl_texcoord4 v8
dcl_texcoord7 v9
dcl_texcoord6 v10
dcl_texcoord2 o0
dcl_texcoord o1.xy
dcl_texcoord3 o2
dcl_texcoord4 o3
dcl_texcoord6 o4
dcl_texcoord5 o5
dcl_position o6
//mov r0.xyz, c12
r0.xyz = MeshExtension
//mad r0.xyz, v0, r0, c11
r0.xyz = position * MeshExtension + MeshOrigin
//add r1.xyw, c10.xyzz, v5.xyzz
r1.xyw = InstancedPreViewTranslation + dcl_texcoord1
mov r2.x, v6.x
mov r2.y, v7.x
mov r2.z, v8.x
mov r2.w, r1.x
mov r0.w, v0.w
dp4 r2.x, r2, r0
r2.x = (v6,v7,v8,r1.x) dot (r0.xyz,v0.w)
r2.y = (v6, v7, v8, r1.y) dot(r0.xyz, v0.w)
r2.z = (v6, v7, v8.z, r1.w) dot(r0.xyz, v0.w)
mad r0, v2, c5.x, c5.y
mad r1.xyz, v1, c5.x, c5.y
mul r3.xyz, r0.zxyw, r1.yzxw
mad r3.xyz, r0.yzxw, r1.zxyw, -r3
mul r3.xyz, r0.w, r3
mul r4, r2.y, c1
mad r4, c0, r2.x, r4
mad r4, c2, r2.z, r4
mad r4, c3, v0.w, r4
mad r5.xyz, r2, -c4.w, c4
dp3 r6.x, r5, v6
dp3 r6.y, r5, v7
dp3 r6.z, r5, v8
mul r5.xyz, r6, v10
dp3 o4.x, r1, r5
dp3 o4.y, r3, r5
dp3 o4.z, r0, r5
abs r0.x, c17.x
if_lt - r0.x, r0.x
add r0.xyz, r2, -c4
dp3 r0.w, r0, r0
rsq r0.w, r0.w
rcp r1.x, r0.w
add r1.x, r1.x, -c13.w
max r1.x, r1.x, c5.z
mul r1.x, r1.x, c13.x
slt r1.y, c5.w, r0_abs.z
lrp r2.w, r1.y, r0.z, c5.w
mul r1.y, r2.w, -c13.y
exp r1.y, r1.y
add r1.y, -r1.y, -c5.y
mul r1.z, r2.w, c13.y
rcp r1.z, r1.z
mul r1.y, r1.z, r1.y
mul r1.x, r1.y, r1.x
mul r0.xyz, r0.w, r0
dp3 r0.x, c16, r0
mad r0.x, r0.x, -c19.x, c19.y
pow r1.y, r0.x, c13.z
mov r0.xyz, c15
add r0.xyz, -r0, c14
mad r0.xyz, r1.y, r0, c15
exp r0.w, -r1.x
min r0.w, r0.w, -c5.y
max r0.w, r0.w, c14.w
add r1.x, -r0.w, -c5.y
mul o3.xyz, r0, r1.x
mov o3.w, r0.w
	else
	add r0.xyz, r2, -c4
	dp3 r0.x, r0, r0
	rsq r0.x, r0.x
	rcp r0.x, r0.x
	mov r1.z, c4.z
	add r3, -r1.z, c16
	sge r0.y, c19.z, r0_abs.z
	lrp r1.x, r0.y, c19.z, r0.z
	rcp r0.y, r1.x
	mul_sat r3, r0.y, r3
	add r1, -r1.z, c18
	mul_sat r1, r0.y, r1
	add r0, r0.x, -c15
	max r0, r0, c5.z
	add r1, -r3, r1
	mul r0, r0, r1_abs
	slt r1, r0, c14
	mul r0, r0, c13
	exp r3.x, r0.x
	exp r3.y, r0.y
	exp r3.z, r0.z
	exp r3.w, r0.w
	mul r0, r1, r3
	mad r1, r1, r3, c5.y
	mul r3.xyz, r1.x, c6
	mov r3.w, r0.x
	mul r3, r0.y, r3
	mad r3.xyz, r1.y, c7, r3
	mul r3, r0.z, r3
	mad r3.xyz, r1.z, c8, r3
	mul r0, r0.w, r3
	mad o3.xyz, r1.w, c9, r0
	mov o3.w, r0.w
	endif
	mov o0, v3
	mov o1.xy, v4
	mov o2, v9
	mov o4.w, r4.z
	mov o5.w, r4.w
	mov o5.xyz, r2
	mov o6, r4

	// approximately 112 instruction slots used
